### ISSUE TITLE
Invalid key files cause abrupt termination

### ISSUE THREAD

**Issue by orancanoren** [orancanoren/CryptographicAlgorithmsSuite#6]
AES encryption in ECB mode abruptly exits if the key file does not contain an IV field.

```bash
cryptoran aes ecb foo -k foo.enc -e

Traceback (most recent call last):
  File "d:\software\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\software\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Software\Anaconda3\Scripts\cryptoran.exe\__main__.py", line 9, in <module>
  File "d:\software\anaconda3\lib\site-packages\cryptoran\__main__.py", line 312, in main
    Cryptoran()
  File "d:\software\anaconda3\lib\site-packages\cryptoran\__main__.py", line 45, in __init__
    getattr(self, args.command)()
  File "d:\software\anaconda3\lib\site-packages\cryptoran\__main__.py", line 244, in aes
    self._blockcipherOperation('aes', blockcipher.AES)
  File "d:\software\anaconda3\lib\site-packages\cryptoran\__main__.py", line 206, in _blockcipherOperation
    key, iv = self._readKey('1', args.k)
ValueError: not enough values to unpack (expected 2, got 0)
```

**Comment by orancanoren** [comment]
I just noticed that the provided key file argument is an invalid one; instead of foo.key I've supplied foo.enc as the key file. Still, this case must be handled better.
